Repository PawseySC/pawsey-spack-config, pull requests merged in 2022-11, with the labels that each got.

#118 Pelahi dev
  setonix/configs/site_allusers/compilers.yaml
  setonix/configs/site_allusers/packages.yaml
  setonix/environments/env_apps/spack.yaml
  setonix/environments/env_astro/spack.yaml
  setonix/environments/env_bench/spack.yaml
  setonix/environments/env_bio/spack.yaml
  setonix/environments/env_devel/spack.yaml
  setonix/environments/env_io_libs/spack.yaml
  setonix/environments/env_langs/spack.yaml
  setonix/environments/env_num_libs/spack.yaml
  setonix/environments/env_python/spack.yaml
  setonix/environments/env_roms/spack.yaml
  setonix/environments/env_s3_clients/spack.yaml
  setonix/environments/env_utils/spack.yaml
  setonix/environments/env_vis/spack.yaml
  setonix/environments/env_wrf/spack.yaml
  setonix/repo/packages/nektar/package.py
  setonix/repo/packages/opencv/dnn_cuda.patch
  setonix/repo/packages/opencv/opencv3.2_cmake.patch
  setonix/repo/packages/opencv/opencv3.2_compiler_cmake.patch
  setonix/repo/packages/opencv/opencv3.2_ffmpeg.patch
  setonix/repo/packages/opencv/opencv3.2_fj.patch
  setonix/repo/packages/opencv/opencv3.2_python3.7.patch
  setonix/repo/packages/opencv/opencv3.2_regacyvtk.patch
  setonix/repo/packages/opencv/opencv3.2_vtk.patch
  setonix/repo/packages/opencv/opencv3_cmakecompileroptions.patch
  setonix/repo/packages/opencv/package.py
  setonix/repo/packages/py-astropy/package.py
  setonix/repo/packages/py-erfa/package.py
  setonix/repo/packages/wcstools/package.py
  setonix/setup_scripts/run_first_python_install.sh
  setonix/setup_scripts/spack_system_package_check.sh
  setonix/setup_scripts/variables.sh
Labels: configuration

#123 update to spack.yamls to include specific py ver
  setonix/environments/env_devel/spack.yaml
  setonix/environments/env_io_libs/spack.yaml
  setonix/environments/env_langs/spack.yaml
  setonix/environments/env_num_libs/spack.yaml
  setonix/environments/env_python/spack.yaml
  setonix/environments/env_s3_clients/spack.yaml
  setonix/environments/env_utils/spack.yaml
Labels: configuration

#124 Update env yamls
  setonix/configs/spackuser_pawseystaff/modules.yaml
  setonix/environments/env_apps/spack.yaml
  setonix/environments/env_astro/spack.yaml
  setonix/environments/env_num_libs/spack.yaml
Labels: configuration

#126 Minor fix to single astro package for python
  setonix/environments/env_astro/spack.yaml
Labels: configuration

#128 Added xpmem to the compiler config
  setonix/configs/site_allusers/compilers.yaml
Labels: configuration

#130 Update to a few recipes related to askap ops
  setonix/environments/env_astro/spack.yaml
  setonix/repo/packages/casacore/package.py
  setonix/repo/packages/libzmq/package.py
Labels: configuration

#132 added different versions of log4cxx
  setonix/configs/spackuser_pawseystaff/modules.yaml
  setonix/environments/env_astro/spack.yaml
Labels: configuration

#135 Fixed missing python dependence
  setonix/environments/env_devel/spack.yaml
Labels: configuration

#136 Remove Python test triggering charm++ build bug
  setonix/repo/packages/charmpp/deserpenticate.patch
  setonix/repo/packages/charmpp/package.py
Labels: bug

#139 Fix for singularity module to properly run MPI
  setonix/templates/modules/modulefile.lua
Labels: configuration

#140 Fixed missing libmunge bind
  setonix/templates/modules/modulefile.lua
Labels: bug

#142 Added script to manage user installations of software
  setonix/setup_scripts/update_user_spack_installs_after_spack_update.sh
Labels: enhancement
