Repository PawseySC/pawsey-spack-config, pull requests merged in 2023-07, with the labels that each got.

#185 Mpi related externals
  systems/setonix/configs/site/packages.yaml
Labels: configuration

#191 Implements build cache.
  scripts/install_environments.sh
  scripts/install_python.sh
  systems/setonix/settings.sh
Labels: enhancement

#193 Environments update
  repo/packages/miniocli/package.py
  repo/packages/rclone/package.py
  systems/setonix/configs/site/packages.yaml
  systems/setonix/configs/spackuser/modules.yaml
  systems/setonix/environments/env_apps/spack.yaml
  systems/setonix/environments/env_io_libs/spack.yaml
  systems/setonix/environments/env_s3_clients/spack.yaml
  systems/setonix/environments/env_wrf/spack.yaml
Labels: bug, configuration
